language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

before_install:
  - echo $TRAVIS_BRANCH

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Wt
  #- sudo apt-get install witty witty-dbg witty-dev witty-doc
  # gcov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Download other prerequisites
  - ./scripts/download_other_githubs
  # Check dead links
  - sudo apt-get install -qq npm
  - npm config set strict-ssl false
  - sudo npm install -g markdown-link-check

services:
 - xvfb

script: 
  # Console test
  - qmake K3OpEenRijConsoleTest.pro
  - make --silent debug
  - ./K3OpEenRijConsoleTest
  # Console
  - qmake K3OpEenRijConsole.pro
  - make --silent debug
  - ./K3OpEenRijConsole
  # Desktop test
  - qmake K3OpEenRijDesktopTest.pro
  - make --silent debug
  - ./K3OpEenRijDesktopTest
  # Desktop
  - qmake K3OpEenRijDesktop.pro
  - make --silent debug
  - ./K3OpEenRijDesktop &
  # Website
  #- qmake K3OpEenRijWebsite.pro
  #- make --silent debug
  #- ./K3OpEenRijWebsite &
  # Check dead links
  - rm .travis.yml
  - ./scripts/check_dead_links
  # Codecov
  - ./get_code_cov > /dev/null
  - codecov > /dev/null
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
