language: cpp
compiler: gcc
sudo: require
dist: trusty

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - echo $TRAVIS_BRANCH
  # C++14
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # Wt
  - sudo apt-get install witty witty-dbg witty-dev witty-doc
  # gcov
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Download other prerequisites
  - ./download_other_githubs

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: 
  # Console test
  - qmake K3OpEenRijConsoleTest.pro
  - make debug
  - ./K3OpEenRijConsoleTest
  # Console
  - qmake K3OpEenRijConsole.pro
  - make debug
  - ./K3OpEenRijConsole
  # Desktop test
  - qmake K3OpEenRijDesktopTest.pro
  - make debug
  - ./K3OpEenRijDesktopTest
  # Desktop
  - qmake K3OpEenRijDesktop.pro
  - make debug
  - ./K3OpEenRijDesktop &
  # Website
  - qmake K3OpEenRijWebsite.pro
  - make debug
  - ./K3OpEenRijWebsite &
  # Codecov
  - ./get_code_cov > /dev/null
  - codecov > /dev/null
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
