language: cpp
dist: xenial
compiler:
  - gcc
  # - clang 

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  - echo $TRAVIS_BRANCH

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Wt
  - sudo apt-get install witty witty-dbg witty-dev witty-doc
  # gcov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint
  # Download other prerequisites
  - ./Scripts/download_other_githubs

services:
 - xvfb

script: 
  # Console test
  - qmake K3OpEenRijConsoleTest.pro
  - make --silent debug
  - ./K3OpEenRijConsoleTest
  # Console
  - qmake K3OpEenRijConsole.pro
  - make --silent debug
  - ./K3OpEenRijConsole
  # Desktop test
  - qmake K3OpEenRijDesktopTest.pro
  - make --silent debug
  - ./K3OpEenRijDesktopTest
  # Desktop
  - qmake K3OpEenRijDesktop.pro
  - make --silent debug
  - ./K3OpEenRijDesktop &
  # Website
  - qmake K3OpEenRijWebsite.pro
  - make --silent debug
  - ./K3OpEenRijWebsite &
  # Codecov
  - ./get_code_cov > /dev/null
  - codecov > /dev/null
  # OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
