sudo: require
language: cpp
compiler: gcc
dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:sonkun/sfml-development
  - sudo pip install codecov

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

install: 
  - sudo apt-get install -qq g++-5  
  - sudo apt-get install libsfml-dev
  - ./install_oclint.sh

before_script:
  - ./download_other_githubs.sh

script: 
  - qmake K3OpEenRijConsole.pro
  - make
  - qmake K3OpEenRijDesktop.pro
  - make
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
