#!/bin/bash

# Go the the K3OpEenRij root folder
cd ..

rm Makefile
rm Makefile.*
rm -r release
rm -r debug
rm ui_*.h
rm qrc_*.cpp
rm moc_*.cpp
rm object_script*.*
rm *_plugin_import.cpp
rm -rf debug
rm -rf release